
INSERT INTO vinyl_author (author) VALUES ('萊納 Fritz Reiner');
INSERT INTO vinyl_author (author) VALUES ('李希特 Sviatoslav Richter');
INSERT INTO vinyl_author (author) VALUES ('王羽佳 Yuja Wang');
INSERT INTO vinyl_author (author) VALUES ('帕華洛帝 Luciano Pavarotti');
INSERT INTO vinyl_author (author) VALUES ('克萊曼 Gidon Kremer');
INSERT INTO vinyl_author (author) VALUES ('吉普森 Alexander Gibson');
INSERT INTO vinyl_author (author) VALUES ('馬友友 Yo-Yo Ma');
INSERT INTO vinyl_author (author) VALUES ('拉圖 Simon Rattle');
INSERT INTO vinyl_author (author) VALUES ('米爾斯坦 Nathan Milstein');
INSERT INTO vinyl_author (author) VALUES ('愛麗絲紗良奧特 Alice Sara Ott');
INSERT INTO vinyl_author (author) VALUES ('小澤征爾 Seiji Ozawa');
INSERT INTO vinyl_author (author) VALUES ('齊瑪曼 Krystian Zimerman');
INSERT INTO vinyl_author (author) VALUES ('提爾森湯瑪斯 Michael Tilson Thomas');
INSERT INTO vinyl_author (author) VALUES ('阿巴多 Claudio Abbado');
INSERT INTO vinyl_author (author) VALUES ('阿優 Felix Ayo');
INSERT INTO vinyl_author (author) VALUES ('安塞美 Ernest Ansermet');
INSERT INTO vinyl_author (author) VALUES ('阿卡多 Salvatore Accardo');
INSERT INTO vinyl_author (author) VALUES ('慕提 Riccardo Muti');
INSERT INTO vinyl_author (author) VALUES ('梅塔 Zubin Mehta');
INSERT INTO vinyl_author (author) VALUES ('蕭提 Sir Georg Solti');
INSERT INTO vinyl_author (author) VALUES ('Tony Ann ');
INSERT INTO vinyl_author (author) VALUES ('夢幻之家四重奏 ');
INSERT INTO vinyl_author (author) VALUES ('提琴雙傑 2Cellos');
INSERT INTO vinyl_author (author) VALUES ('安德烈波伽利 Andrea Bocelli');
INSERT INTO vinyl_author (author) VALUES ('卡拉絲 Maria Callas');
INSERT INTO vinyl_author (author) VALUES ('杜普蕾 Jacqueline du Pre');
INSERT INTO vinyl_author (author) VALUES ('卡拉揚 Herbert von Karajan');
INSERT INTO vinyl_author (author) VALUES ('索柯洛夫 Grigory Sokolov');
INSERT INTO vinyl_author (author) VALUES ('約翰約漢生 John Johnsson');
INSERT INTO vinyl_author (author) VALUES ('芙蕾妮 Freni');
INSERT INTO vinyl_author (author) VALUES ('馬辛 Marcin');
INSERT INTO vinyl_author (author) VALUES ('歐拉夫亞諾茲 Olafur Arnalds');
INSERT INTO vinyl_author (author) VALUES ('斯諾里霍格利森 Snorri Hallgrimsson');
INSERT INTO vinyl_author (author) VALUES ('任奫燦 Yunchan Lim');
INSERT INTO vinyl_author (author) VALUES ('角野隼斗 Hayato Sumino');
INSERT INTO vinyl_author (author) VALUES ('郎朗 Lang Lang');
INSERT INTO vinyl_author (author) VALUES ('歐拉夫森 Vikingur Olafsson');
INSERT INTO vinyl_author (author) VALUES ('劉曉禹 Bruce Liu');
INSERT INTO vinyl_author (author) VALUES ('特里福諾夫 Daniil Trifonov');
INSERT INTO vinyl_author (author) VALUES ('陳銳 Ray Chen');
INSERT INTO vinyl_author (author) VALUES ('約翰威廉斯 John Williams');
INSERT INTO vinyl_author (author) VALUES ('亞歷克西斯弗倫奇 Alexis Ffrench');
INSERT INTO vinyl_author (author) VALUES ('Various');
INSERT INTO vinyl_author (author) VALUES ('顧爾達 Friedrich Gulda');
INSERT INTO vinyl_author (author) VALUES ('庫貝利克 Rafael Kubelik');
INSERT INTO vinyl_author (author) VALUES ('波里尼 Maurizio Pollini');
INSERT INTO vinyl_author (author) VALUES ('羅傑伊諾 Roger Eno');
INSERT INTO vinyl_author (author) VALUES ('班乃德提 Nicola Benedetti');
INSERT INTO vinyl_author (author) VALUES ('萊斯戴斯納 Bryce Dessner');
INSERT INTO vinyl_author (author) VALUES ('歐伊斯特拉夫 David Oistrakh');
INSERT INTO vinyl_author (author) VALUES ('朱里尼 Carlo Maria Giulini');
INSERT INTO vinyl_author (author) VALUES ('多莉艾莫絲 Tori Amos');
INSERT INTO vinyl_author (author) VALUES ('馬克斯李希特 Max Richter');
INSERT INTO vinyl_author (author) VALUES ('艾奧迪 Ludovico Einaudi');
INSERT INTO vinyl_author (author) VALUES ('帕爾曼 Itzhak Perlman');
INSERT INTO vinyl_author (author) VALUES ('瑪麗薩穆爾森 Mari Samuelsen');
INSERT INTO vinyl_author (author) VALUES ('富蘭梭瓦 Francois Samson');
INSERT INTO vinyl_author (author) VALUES ('哈德利希 Augustin Hadelich');
INSERT INTO vinyl_author (author) VALUES ('娜妲莉史都茲曼 Nathalie Stutzmann');
INSERT INTO vinyl_author (author) VALUES ('安赫麗絲 Victoria De Los Angeles');
INSERT INTO vinyl_author (author) VALUES ('阿格麗希 Martha Argerich');
INSERT INTO vinyl_author (author) VALUES ('伊莎塔 Isata Kanneh-Mason');
INSERT INTO vinyl_author (author) VALUES ('沙馬尤 Bertrand Chamayou');
INSERT INTO vinyl_author (author) VALUES ('Maurice Ravel');
INSERT INTO vinyl_author (author) VALUES ('薛庫 Sheku Kanneh-Mason');
INSERT INTO vinyl_author (author) VALUES ('瑪爾茨 Johanna Martzy');
INSERT INTO vinyl_author (author) VALUES ('麥凱萊 Klaus Makela');
INSERT INTO vinyl_author (author) VALUES ('丹尼爾霍普 Daniel Hope');
INSERT INTO vinyl_author (author) VALUES ('貝姆 Karl Bohm');
INSERT INTO vinyl_author (author) VALUES ('喬登雷凱 Jordan Rakei');
INSERT INTO vinyl_author (author) VALUES ('白墨河樂團 Balmorhea');
INSERT INTO vinyl_author (author) VALUES ('希拉蕊韓 Hilary Hahn');
INSERT INTO vinyl_author (author) VALUES ('Pyotr Ilyich Tchaikovsky');
INSERT INTO vinyl_author (author) VALUES ('慕特 Anne-Sophie Mutter');
INSERT INTO vinyl_author (author) VALUES ('羅斯托波維奇 Mstislav Rostropovich');
INSERT INTO vinyl_author (author) VALUES ('艾迪雷德梅尼 Eddie Redmayne');
INSERT INTO vinyl_author (author) VALUES ('葛羅斯文諾 Benjamin Grosvenor');
INSERT INTO vinyl_author (author) VALUES ('艾蘭庫柏 Erland Cooper');
INSERT INTO vinyl_author (author) VALUES ('巴倫波因 Daniel Barenboim');
INSERT INTO vinyl_author (author) VALUES ('久石讓 Joe Hisaishi');
INSERT INTO vinyl_author (author) VALUES ('喬治溫斯頓 George Winston');
INSERT INTO vinyl_author (author) VALUES ('崔佛霍恩 Trevor Horn');
INSERT INTO vinyl_author (author) VALUES ('維克多歐利阿納森 Viktor Orri Arnason');
INSERT INTO vinyl_author (author) VALUES ('約普貝凡 Joep Beving');
INSERT INTO vinyl_author (author) VALUES ('傑夫高布倫 Jeff Goldblum');
INSERT INTO vinyl_author (author) VALUES ('吉妮楊森 Janine Jansen');
INSERT INTO vinyl_author (author) VALUES ('提鮑德 Jean-Yves Thibaudet');
INSERT INTO vinyl_author (author) VALUES ('茱麗葉葛芮柯 Juliette Greco');
INSERT INTO vinyl_author (author) VALUES ('葛莉茉 Helene Grimaud');
INSERT INTO vinyl_author (author) VALUES ('篷車隊樂團 Caravan');
INSERT INTO vinyl_author (author) VALUES ('羅梅洛吉他四重奏 Los Romeros');
INSERT INTO vinyl_author (author) VALUES ('范宗沛 ');
INSERT INTO vinyl_author (author) VALUES ('王雁盟 ');
INSERT INTO vinyl_author (author) VALUES ('十鼓擊樂團 ');
INSERT INTO vinyl_author (author) VALUES ('李哲藝 Che-Yi Lee');
INSERT INTO vinyl_author (author) VALUES ('提勒曼 Christian Thielemann');
INSERT INTO vinyl_author (author) VALUES ('雅諾史卡合奏團 Janoska Ensemble');
INSERT INTO vinyl_author (author) VALUES ('奧拉雅羅 Ola Gjeilo');
INSERT INTO vinyl_author (author) VALUES ('皮爾斯 Sir Peter Pears');
INSERT INTO vinyl_author (author) VALUES ('史蒂芬莫奇歐 Stephan Moccio');
INSERT INTO vinyl_author (author) VALUES ('費茲樂團 Fizz');
INSERT INTO vinyl_author (author) VALUES ('亞尼克聶澤塞金 Yannick Nezet Seguin');
INSERT INTO vinyl_author (author) VALUES ('威廉史坦伯格 William Steinberg');
INSERT INTO vinyl_author (author) VALUES ('琳西特莉 Lindsey Stirling');
INSERT INTO vinyl_author (author) VALUES ('高提耶卡普松 Gautier Capucon');
INSERT INTO vinyl_author (author) VALUES ('劍橋國王學院合唱團 Choir of Kings College Cambridge');
INSERT INTO vinyl_author (author) VALUES ('詹姆斯拉斯特 James Last');
INSERT INTO vinyl_author (author) VALUES ('伯恩斯坦 Leonard Bernstein');
INSERT INTO vinyl_author (author) VALUES ('吉利爾斯 Emil Gilels');
INSERT INTO vinyl_author (author) VALUES ('馬丁史岱費爾德 Martin Stadtfeld');
INSERT INTO vinyl_author (author) VALUES ('詹姆斯紐頓霍華 James Newton Howard');
INSERT INTO vinyl_author (author) VALUES ('馬提歐明德威克 Matteo Myderwyk');
INSERT INTO vinyl_author (author) VALUES ('泰特曼 Jonathan Tetelman');
INSERT INTO vinyl_author (author) VALUES ('史帝法諾柏那尼 Stefano Bollani');
INSERT INTO vinyl_author (author) VALUES ('麗絲戴維森 Lise Davidsen');
INSERT INTO vinyl_author (author) VALUES ('歐萊利 Christopher O''Riley');
INSERT INTO vinyl_author (author) VALUES ('克倫培勒 Otto Klemperer');
INSERT INTO vinyl_author (author) VALUES ('安娜拉普伍德 Anna Lapwood');
INSERT INTO vinyl_author (author) VALUES ('易碎動物 Glass Animals');
INSERT INTO vinyl_author (author) VALUES ('埃絲特阿伯拉米 Esther Abrami');
INSERT INTO vinyl_author (author) VALUES ('薩洛 Alexandre Tharaud');
INSERT INTO vinyl_author (author) VALUES ('小克萊巴 Carlos Kleiber');
INSERT INTO vinyl_author (author) VALUES ('Erasure');
INSERT INTO vinyl_author (author) VALUES ('利謝茲基 Jan Lisiecki');
INSERT INTO vinyl_author (author) VALUES ('穆拉汶斯基 Mravinsky');
INSERT INTO vinyl_author (author) VALUES ('契可里尼 Aldo Ciccolini');
INSERT INTO vinyl_author (author) VALUES ('福特萬格勒 Wilhelm Furtwangler');
INSERT INTO vinyl_author (author) VALUES ('塞爾 George Szell');
INSERT INTO vinyl_author (author) VALUES ('魔比 Moby');
INSERT INTO vinyl_author (author) VALUES ('克利斯欽賈維 Kristjan Jarvi');
INSERT INTO vinyl_author (author) VALUES ('紀新 Evgeny Kissin');
INSERT INTO vinyl_author (author) VALUES ('孟許 Charles Munch');
INSERT INTO vinyl_author (author) VALUES ('雷諾卡普松 Renaud Capucon');
INSERT INTO vinyl_author (author) VALUES ('舒娃茲柯芙 Elisabeth Schwarzkopf');
INSERT INTO vinyl_author (author) VALUES ('肯培 Rudolf Kempe');
INSERT INTO vinyl_author (author) VALUES ('杜拉第 Antal Dorati');
INSERT INTO vinyl_author (author) VALUES ('普列文 Andre Previn');
INSERT INTO vinyl_author (author) VALUES ('考夫曼 Jonas Kaufmann');
INSERT INTO vinyl_author (author) VALUES ('多明哥 Placido Domingo');
INSERT INTO vinyl_author (author) VALUES ('哈農庫特 Nikolaus Harnoncourt');
INSERT INTO vinyl_author (author) VALUES ('美空雲雀 ');
INSERT INTO vinyl_author (author) VALUES ('賀比漢考克 Herbie Hancock');
INSERT INTO vinyl_author (author) VALUES ('比爾艾文斯 Bill Evans');
INSERT INTO vinyl_author (author) VALUES ('史坦蓋茲 Stan Getz');
INSERT INTO vinyl_author (author) VALUES ('戴夫布魯貝克 Dave Brubeck');
INSERT INTO vinyl_author (author) VALUES ('貝拉方提 Harry Belafonte');
INSERT INTO vinyl_author (author) VALUES ('邁爾士戴維斯 Miles Davis');
INSERT INTO vinyl_author (author) VALUES ('瓊拜雅 Joan Baez');
INSERT INTO vinyl_author (author) VALUES ('菅野邦彥 ');
INSERT INTO vinyl_author (author) VALUES ('美樂蒂佳朵 Melody Gardot');
INSERT INTO vinyl_author (author) VALUES ('麥克布萊德 Christian McBride');
INSERT INTO vinyl_author (author) VALUES ('鈴木勳 Isao Suzuki');
INSERT INTO vinyl_author (author) VALUES ('亞莎莉亞艾芙拉 Cesaria Evora');
INSERT INTO vinyl_author (author) VALUES ('莎拉 K. Sara K.');
INSERT INTO vinyl_author (author) VALUES ('Moon Haewon ');
INSERT INTO vinyl_author (author) VALUES ('安全地帶 ');
INSERT INTO vinyl_author (author) VALUES ('艾靈頓公爵 Duke Ellington');
INSERT INTO vinyl_author (author) VALUES ('顏尼歐莫利克奈 Ennio Morricone');
INSERT INTO vinyl_author (author) VALUES ('山本剛 Tsuyoshi Yamamoto');
INSERT INTO vinyl_author (author) VALUES ('以莉高露 ');
INSERT INTO vinyl_author (author) VALUES ('羅卡透內芙 Radka Toneff');
INSERT INTO vinyl_author (author) VALUES ('No Artist');
INSERT INTO vinyl_author (author) VALUES ('日野元彥 ');
INSERT INTO vinyl_author (author) VALUES ('峰厚介 ');
INSERT INTO vinyl_author (author) VALUES ('史黛西肯特 Stacey Kent');
INSERT INTO vinyl_author (author) VALUES ('玉置浩二 Koji Tamaki');
INSERT INTO vinyl_author (author) VALUES ('鬼太鼓座 Ondekoza');
INSERT INTO vinyl_author (author) VALUES ('石川小百合 ');
INSERT INTO vinyl_author (author) VALUES ('芭芭拉史翠珊 Barbra Streisand');
INSERT INTO vinyl_author (author) VALUES ('Trio de Curda ');
INSERT INTO vinyl_author (author) VALUES ('卡拉布妮 Carla Bruni');
INSERT INTO vinyl_author (author) VALUES ('蕾貝卡碧瑾 Rebecca Pidgeon');
INSERT INTO vinyl_author (author) VALUES ('Antonio Vivaldi Liszt Ferenc Chamber Orchestra');
INSERT INTO vinyl_author (author) VALUES ('安娜卡蘭 Ana Caram');
INSERT INTO vinyl_author (author) VALUES ('谷村新司 ');
INSERT INTO vinyl_author (author) VALUES ('夏川里美 Rimi Natsukawa');
INSERT INTO vinyl_author (author) VALUES ('席夢卡麥兒 Simone Kopmajer');
INSERT INTO vinyl_author (author) VALUES ('伊娃凱希蒂 Eva Cassidy');
INSERT INTO vinyl_author (author) VALUES ('Lady Blackbird ');
INSERT INTO vinyl_author (author) VALUES ('雅尼杜納魯斯 Arne Domnerus');
INSERT INTO vinyl_author (author) VALUES ('寺島靖國 ');
INSERT INTO vinyl_author (author) VALUES ('艾爾迪謬拉 Al Di Meola');
INSERT INTO vinyl_author (author) VALUES ('史考特漢米爾頓 Scott Hamilton');
INSERT INTO vinyl_author (author) VALUES ('派翠西亞巴伯 Patricia Barber');
INSERT INTO vinyl_author (author) VALUES ('趙聰 ');
INSERT INTO vinyl_author (author) VALUES ('伊布拉印飛列 Ibrahim Ferrer');
INSERT INTO vinyl_author (author) VALUES ('史考第萊特 Scotty Wright');
INSERT INTO vinyl_author (author) VALUES ('中村照夫 Teruo Nakamura');
INSERT INTO vinyl_author (author) VALUES ('蒙堤亞歷山大 Monty Alexander');
INSERT INTO vinyl_author (author) VALUES ('艾迪希金斯 Eddie Higgins');
INSERT INTO vinyl_author (author) VALUES ('細川綾子 Ayako Hosokawa');
INSERT INTO vinyl_author (author) VALUES ('艾莉森克勞絲 Alison Krauss');
INSERT INTO vinyl_author (author) VALUES ('金美人 Aisyah');
INSERT INTO vinyl_author (author) VALUES ('Mao Ya');
INSERT INTO vinyl_author (author) VALUES ('瑪麗黑 Mary Black');
INSERT INTO vinyl_author (author) VALUES ('戈探計劃 Gotan Project');
INSERT INTO vinyl_author (author) VALUES ('安佐里 Ann Sally');
INSERT INTO vinyl_author (author) VALUES ('Ann Sally');
INSERT INTO vinyl_author (author) VALUES ('遠景俱樂部 Buena Vista Social Club');
INSERT INTO vinyl_author (author) VALUES ('世故女子爵士四重奏 Sophisticated Lady Jazz Quartet');
INSERT INTO vinyl_author (author) VALUES ('瑪黛琳 Madeleine Peyroux');
INSERT INTO vinyl_author (author) VALUES ('克雷格雷翁 Craig Leon');
INSERT INTO vinyl_author (author) VALUES ('Peter, Paul & Mary');
INSERT INTO vinyl_author (author) VALUES ('辛蒂羅波 Cyndi Lauper');
INSERT INTO vinyl_author (author) VALUES ('班尼固德曼 Benny Goodman');
INSERT INTO vinyl_author (author) VALUES ('芭菠楊格 Barb Jungr');
INSERT INTO vinyl_author (author) VALUES ('五輪真弓 Itsuwa Mayumi');
INSERT INTO vinyl_author (author) VALUES ('甘蒂絲史普琳絲 Kandace Springs');
INSERT INTO vinyl_author (author) VALUES ('席娜艾格 Sinne Eeg');
INSERT INTO vinyl_author (author) VALUES ('帕可迪魯奇亞 Paco De Lucia');
INSERT INTO vinyl_author (author) VALUES ('安碧森 Anne Bisson');
INSERT INTO vinyl_author (author) VALUES ('尾島由郎 Yoshio Ojima');
INSERT INTO vinyl_author (author) VALUES ('坂本龍一 Ryuichi Sakamoto');
INSERT INTO vinyl_author (author) VALUES ('埃德加尼赫特 Edgar Knecht');
INSERT INTO vinyl_author (author) VALUES ('歐瑪拉 Omara Portuondo');
INSERT INTO vinyl_author (author) VALUES ('伯特巴克瑞克 Burt Bacharach');
INSERT INTO vinyl_author (author) VALUES ('安潔莉克琪帝歐 Angelique Kidjo');
INSERT INTO vinyl_author (author) VALUES ('藤田惠美 Emi Fujita');
INSERT INTO vinyl_author (author) VALUES ('愛無限大樂團 Love Unlimited Orchestra');
INSERT INTO vinyl_author (author) VALUES ('珍妮佛華恩斯 Jennifer Warnes');
INSERT INTO vinyl_author (author) VALUES ('凡妮莎斐迪南 Vanessa Fernandez');
INSERT INTO vinyl_author (author) VALUES ('唐倫德爾 Don Rendell');
INSERT INTO vinyl_author (author) VALUES ('奧利維亞頌瑪 Olivia Trummer');
INSERT INTO vinyl_author (author) VALUES ('瑪麗亞馬凱絲妮 Maria Markesini');
INSERT INTO vinyl_author (author) VALUES ('希爾德路易絲艾絲庇恩森 Hilde Louise Asbjornsen');
INSERT INTO vinyl_author (author) VALUES ('茱蒂柯林斯 Judy Collins');
INSERT INTO vinyl_author (author) VALUES ('Bruce Katz Band ');
INSERT INTO vinyl_author (author) VALUES ('麥克歐菲爾德 Mike Oldfield');
INSERT INTO vinyl_author (author) VALUES ('賽門與葛芬柯 Simon & Garfunkel');
INSERT INTO vinyl_author (author) VALUES ('馬渕侑子三重奏 Yuko Mabuchi Trio');
INSERT INTO vinyl_author (author) VALUES ('阿尼杜納魯斯&葛斯塔夫索維斯特 Arne Domnerus & Gustaf Sjokvist');
INSERT INTO vinyl_author (author) VALUES ('細野晴臣 Haruomi Hosono');
INSERT INTO vinyl_author (author) VALUES ('蜜可 Meiko');
INSERT INTO vinyl_author (author) VALUES ('彼德艾德頓 Pete Alderton');
INSERT INTO vinyl_author (author) VALUES ('瑟希兒麥可羅恩 Cecile Mclorin Salvant');
INSERT INTO vinyl_author (author) VALUES ('費里特奧德曼 Ferit Odman');
INSERT INTO vinyl_author (author) VALUES ('桑卓布瑞特蘭 Sondre Bratland');
INSERT INTO vinyl_author (author) VALUES ('莉莎迪蘭 Lisa Dillan');
INSERT INTO vinyl_author (author) VALUES ('潔辛塔 Jacintha');
INSERT INTO vinyl_author (author) VALUES ('陳永淘 ');
INSERT INTO vinyl_author (author) VALUES ('橫內章次三重奏&田代百合 hoji Yokouchi Trio&Yuri Tashiro');
INSERT INTO vinyl_author (author) VALUES ('瑪莉雅 Malia');
INSERT INTO vinyl_author (author) VALUES ('Isao Suzuki Trio Isao Suzuki Quartet');
INSERT INTO vinyl_author (author) VALUES ('風暴女神 Storm Large');
INSERT INTO vinyl_author (author) VALUES ('米榭李格蘭 Michel Legrand');
INSERT INTO vinyl_author (author) VALUES ('莎拉克勞克蘭 Sarah McLachlan');
INSERT INTO vinyl_author (author) VALUES ('巴布馬利 Bob Marley');
INSERT INTO vinyl_author (author) VALUES ('列芙瑪麗亞羅謹與海格連 Live Maria Roggen & Helge Lien');
INSERT INTO vinyl_author (author) VALUES ('荷莉蔻兒 Holly Cole');
INSERT INTO vinyl_author (author) VALUES ('娜木拉 ');
INSERT INTO vinyl_author (author) VALUES ('非凡組合 Friend N Fellow');
INSERT INTO vinyl_author (author) VALUES ('何訓田 ');
INSERT INTO vinyl_author (author) VALUES ('艾利森莫耶 Alison Moyet');
INSERT INTO vinyl_author (author) VALUES ('黛娜華盛頓 Dinah Washington');
INSERT INTO vinyl_author (author) VALUES ('連珮如 PeiJu Lien - Pipa');
INSERT INTO vinyl_author (author) VALUES ('霧裡看花打擊樂合奏團 Smoke & Mirrors Percussion Ensemble');
INSERT INTO vinyl_author (author) VALUES ('卡蘿姬 Carol Kidd');
INSERT INTO vinyl_author (author) VALUES ('托比海耶斯 Tubby Hayes');
INSERT INTO vinyl_author (author) VALUES ('米爾特傑克森 Milt Jackson');
INSERT INTO vinyl_author (author) VALUES ('艾拉費茲潔拉 Ella Fitzgerald');
INSERT INTO vinyl_author (author) VALUES ('上原廣美 Hiromi');
INSERT INTO vinyl_author (author) VALUES ('查爾斯明格斯 Charles Mingus');
INSERT INTO vinyl_author (author) VALUES ('諾拉瓊絲 Norah Jones');
INSERT INTO vinyl_author (author) VALUES ('桑尼羅林斯 Sonny Rollins');
INSERT INTO vinyl_author (author) VALUES ('Sonny Rollins');
INSERT INTO vinyl_author (author) VALUES ('查特貝克 Chet Baker');
INSERT INTO vinyl_author (author) VALUES ('瑟隆尼斯孟克 Thelonious Monk');
INSERT INTO vinyl_author (author) VALUES ('約翰柯川 John Coltrane');
INSERT INTO vinyl_author (author) VALUES ('強巴提斯 Jon Batiste');
INSERT INTO vinyl_author (author) VALUES ('法蘭克辛納屈 Frank Sinatra');
INSERT INTO vinyl_author (author) VALUES ('戴安娜克瑞兒 Diana Krall');
INSERT INTO vinyl_author (author) VALUES ('米爾頓納西門托 Milton Nascimento');
INSERT INTO vinyl_author (author) VALUES ('莎拉沃恩 Sarah Vaughan');
INSERT INTO vinyl_author (author) VALUES ('莎瑪拉 Samara Joy');
INSERT INTO vinyl_author (author) VALUES ('肯尼布瑞爾 Kenny Burrell');
INSERT INTO vinyl_author (author) VALUES ('羅允宣 ');
INSERT INTO vinyl_author (author) VALUES ('尤妲希普 Jutta Hipp');
INSERT INTO vinyl_author (author) VALUES ('自由鳥蜜雪兒 Meshell Ndegeocello');
INSERT INTO vinyl_author (author) VALUES ('傑利莫里根 Gerry Mulligan');
INSERT INTO vinyl_author (author) VALUES ('史提夫汪達 Stevie Wonder');
INSERT INTO vinyl_author (author) VALUES ('查爾斯洛伊德 Charles Lloyd');
INSERT INTO vinyl_author (author) VALUES ('路易斯阿姆斯壯 Louis Armstrong');
INSERT INTO vinyl_author (author) VALUES ('阿魯吉阿夫塔伯 Arooj Aftab');
INSERT INTO vinyl_author (author) VALUES ('多米與貝克 Domi & JD Beck');
INSERT INTO vinyl_author (author) VALUES ('吉米史密斯 Jimmy Smith');
INSERT INTO vinyl_author (author) VALUES ('妮娜西蒙 Nina Simone');
INSERT INTO vinyl_author (author) VALUES ('艾莉絲柯川 Alice Coltrane');
INSERT INTO vinyl_author (author) VALUES ('約瑟夫登馬莫德 Mo Kolours');
INSERT INTO vinyl_author (author) VALUES ('Laufey ');
INSERT INTO vinyl_author (author) VALUES ('喬亨德森 Joe Henderson');
INSERT INTO vinyl_author (author) VALUES ('葛雷哥萊波特 Gregory Porter');
INSERT INTO vinyl_author (author) VALUES ('克提斯史泰格斯 Curtis Stigers');
INSERT INTO vinyl_author (author) VALUES ('新爵士大樂團 The New Jazz Orchestra');
INSERT INTO vinyl_author (author) VALUES ('蘿貝塔弗萊克 Roberta Flack');
INSERT INTO vinyl_author (author) VALUES ('凱斯傑瑞特 Keith Jarrett');
INSERT INTO vinyl_author (author) VALUES ('石川晶 ');
INSERT INTO vinyl_author (author) VALUES ('宮間利之 ');
INSERT INTO vinyl_author (author) VALUES ('稲垣次郎 Jiro Inagaki');
INSERT INTO vinyl_author (author) VALUES ('比莉哈樂黛 Billie Holiday');
INSERT INTO vinyl_author (author) VALUES ('霍瑞斯席佛 Horace Silver');
INSERT INTO vinyl_author (author) VALUES ('柯曼霍金斯 Coleman Hawkins');
INSERT INTO vinyl_author (author) VALUES ('提納布魯克斯 Tina Brooks');
INSERT INTO vinyl_author (author) VALUES ('傑米羅奎爾 Jamiroquai');
INSERT INTO vinyl_author (author) VALUES ('Matthew Halsall ');
INSERT INTO vinyl_author (author) VALUES ('史提夫雷梵 Stevie Ray Vaughan');
INSERT INTO vinyl_author (author) VALUES ('米利瓦尼利 Milli Vanilli');
INSERT INTO vinyl_author (author) VALUES ('甘蒂達芙 Candy Dulfer');
INSERT INTO vinyl_author (author) VALUES ('阿提米絲 Artemis');
INSERT INTO vinyl_author (author) VALUES ('巴迪蓋伊 Buddy Guy');
INSERT INTO vinyl_author (author) VALUES ('查理帕克 Charlie Parker');
INSERT INTO vinyl_author (author) VALUES ('克里斯伯堤 Chris Botti');
INSERT INTO vinyl_author (author) VALUES ('尼克德瑞克 Nick Drake');
INSERT INTO vinyl_author (author) VALUES ('謎幻樂團 Imagine Dragons');
INSERT INTO vinyl_author (author) VALUES ('艾維奇 Avicii');
INSERT INTO vinyl_author (author) VALUES ('d4vd ');
INSERT INTO vinyl_author (author) VALUES ('威肯 The Weeknd');
INSERT INTO vinyl_author (author) VALUES ('寵物店男孩 Pet Shop Boys');
INSERT INTO vinyl_author (author) VALUES ('靡靡之音 Hooverphonic');
INSERT INTO vinyl_author (author) VALUES ('險峻海峽合唱團 Dire Straits');
INSERT INTO vinyl_author (author) VALUES ('布勒合唱團 Blur');
INSERT INTO vinyl_author (author) VALUES ('席琳娜 Selena Gomez');
INSERT INTO vinyl_author (author) VALUES ('亞莉安娜 Ariana Grande');
INSERT INTO vinyl_author (author) VALUES ('莎賓娜 Sabrina Carpenter');
INSERT INTO vinyl_author (author) VALUES ('連恩蓋勒格 Liam Gallagher');
INSERT INTO vinyl_author (author) VALUES ('艾力克萊普頓 Eric Clapton');
INSERT INTO vinyl_author (author) VALUES ('席琳狄翁 Celine Dion');
INSERT INTO vinyl_author (author) VALUES ('麥可布雷 Michael Buble');
INSERT INTO vinyl_author (author) VALUES ('杜娃黎波 Dua Lipa');
INSERT INTO vinyl_author (author) VALUES ('非凡人物樂團 The Smashing Pumpkins');
INSERT INTO vinyl_author (author) VALUES ('道希 Doechii');
INSERT INTO vinyl_author (author) VALUES ('查普爾羅恩 Chappell Roan');
INSERT INTO vinyl_author (author) VALUES ('凱蒂佩芮 Katy Perry');
INSERT INTO vinyl_author (author) VALUES ('女神卡卡 Lady Gaga');
INSERT INTO vinyl_author (author) VALUES ('酷娃恰莉 Charli XCX');
INSERT INTO vinyl_author (author) VALUES ('致命誘惑樂團 Within Temptation');
INSERT INTO vinyl_author (author) VALUES ('約翰傳奇 John Legend');
INSERT INTO vinyl_author (author) VALUES ('菲尼亞斯 Finneas');
INSERT INTO vinyl_author (author) VALUES ('阿姆 Eminem');
INSERT INTO vinyl_author (author) VALUES ('October London ');
INSERT INTO vinyl_author (author) VALUES ('德瑞克 Drake');
INSERT INTO vinyl_author (author) VALUES ('蟑螂老爹 Papa Roach');
INSERT INTO vinyl_author (author) VALUES ('麥克米勒 Mac Miller');
INSERT INTO vinyl_author (author) VALUES ('瑪麗亞凱莉 Mariah Carey');
INSERT INTO vinyl_author (author) VALUES ('海爾希 Halsey');
INSERT INTO vinyl_author (author) VALUES ('神韻合唱團 The Verve');
INSERT INTO vinyl_author (author) VALUES ('致命情人合唱團 Bullet For My Valentine');
INSERT INTO vinyl_author (author) VALUES ('靈魂拾荒者 Rag''n''Bone Man');
INSERT INTO vinyl_author (author) VALUES ('肯卓克拉瑪 Kendrick Lamar');
INSERT INTO vinyl_author (author) VALUES ('蘿莎莉雅 Rosalia');
INSERT INTO vinyl_author (author) VALUES ('蜜桃貓朵佳 Doja Cat');
INSERT INTO vinyl_author (author) VALUES ('紫迪斯可機器 Purple Disco Machine');
INSERT INTO vinyl_author (author) VALUES ('橘郡雷克斯 Rex Orange County');
INSERT INTO vinyl_author (author) VALUES ('威利尼爾森 Willie Nelson');
INSERT INTO vinyl_author (author) VALUES ('猶太祭司 Judas Priest');
INSERT INTO vinyl_author (author) VALUES ('H.E.R. ');
INSERT INTO vinyl_author (author) VALUES ('接招合唱團 Take That');
INSERT INTO vinyl_author (author) VALUES ('發亮種子合唱團 The Lightning Seeds');
INSERT INTO vinyl_author (author) VALUES ('女童軍手冊 Scouting For Girls');
INSERT INTO vinyl_author (author) VALUES ('結婚禮物樂團 The Wedding Present');
INSERT INTO vinyl_author (author) VALUES ('合成芽合唱團 Prefab Sprout');
INSERT INTO vinyl_author (author) VALUES ('嘻哈鬥牛梗 Pitbull');
INSERT INTO vinyl_author (author) VALUES ('追隨者合唱團 Train');
INSERT INTO vinyl_author (author) VALUES ('未來小子 Future');
INSERT INTO vinyl_author (author) VALUES ('克里斯小子 Chris Brown');
INSERT INTO vinyl_author (author) VALUES ('飛越地平線樂團 Bring Me The Horizon');
INSERT INTO vinyl_author (author) VALUES ('格蕾西亞柏拉罕 Gracie Abrams');
INSERT INTO vinyl_author (author) VALUES ('渾合唱團 Wham!');
INSERT INTO vinyl_author (author) VALUES ('唐納葛洛佛 Childish Gambino');
INSERT INTO vinyl_author (author) VALUES ('路瑟范德魯斯 Luther Vandross');
INSERT INTO vinyl_author (author) VALUES ('利思羅斯 Leith Ross');
INSERT INTO vinyl_author (author) VALUES ('皇后合唱團 Queen');
INSERT INTO vinyl_author (author) VALUES ('詹姆斯貝 James Bay');
INSERT INTO vinyl_author (author) VALUES ('托托合唱團 Toto');
INSERT INTO vinyl_author (author) VALUES ('LSD ');
INSERT INTO vinyl_author (author) VALUES ('席亞拉 Ciara');
INSERT INTO vinyl_author (author) VALUES ('莎拉芭瑞黎絲 Sara Bareilles');
INSERT INTO vinyl_author (author) VALUES ('絲絨左輪 Velvet Revolver');
INSERT INTO vinyl_author (author) VALUES ('貝汀菲兒 Natasha Bedingfield');
INSERT INTO vinyl_author (author) VALUES ('上帝羔羊樂團 LAMB OF GOD');
INSERT INTO vinyl_author (author) VALUES ('莎黛 Sade');
INSERT INTO vinyl_author (author) VALUES ('凱莉克萊森 Kelly Clarkson');
INSERT INTO vinyl_author (author) VALUES ('流行尖端 Depeche Mode');
INSERT INTO vinyl_author (author) VALUES ('大衛吉爾摩 David Gilmour');
INSERT INTO vinyl_author (author) VALUES ('吉米罕醉克斯 Jimi Hendrix');
INSERT INTO vinyl_author (author) VALUES ('路克康柏斯 Luke Combs');
INSERT INTO vinyl_author (author) VALUES ('肯尼羅傑斯 Kenny Rogers');
INSERT INTO vinyl_author (author) VALUES ('阿巴合唱團 ABBA');
INSERT INTO vinyl_author (author) VALUES ('聯合公園 Linkin Park');
INSERT INTO vinyl_author (author) VALUES ('大衛鮑伊 David Bowie');
INSERT INTO vinyl_author (author) VALUES ('亞瑟小子 Usher');
INSERT INTO vinyl_author (author) VALUES ('惠妮休斯頓 Whitney Houston');
INSERT INTO vinyl_author (author) VALUES ('小紅莓合唱團 The Cranberries');
INSERT INTO vinyl_author (author) VALUES ('紅髮艾德 Ed Sheeran');
INSERT INTO vinyl_author (author) VALUES ('泰勒絲 Taylor Swift');
INSERT INTO vinyl_author (author) VALUES ('托蕾凱莉 Tori Kelly');
INSERT INTO vinyl_author (author) VALUES ('萊諾李奇 Lionel Richie');
INSERT INTO vinyl_author (author) VALUES ('尚恩曼德斯 Shawn Mendes');
INSERT INTO vinyl_author (author) VALUES ('帕洛瑪費絲 Paloma Faith');
INSERT INTO vinyl_author (author) VALUES ('幸運兒達耶 Lucky Daye');
INSERT INTO vinyl_author (author) VALUES ('卡薩比恩 Kasabian');
INSERT INTO vinyl_author (author) VALUES ('崔維斯史考特 Travis Scott');
INSERT INTO vinyl_author (author) VALUES ('湯姆瓊斯 Tom Jones');
INSERT INTO vinyl_author (author) VALUES ('年輕歲月合唱團 Green Day');
INSERT INTO vinyl_author (author) VALUES ('萊恩比提 Ryan Beatty');
INSERT INTO vinyl_author (author) VALUES ('瑪姬蘿潔絲 Maggie Rogers');
INSERT INTO vinyl_author (author) VALUES ('希雅 Sia');
INSERT INTO vinyl_author (author) VALUES ('閃靈樂團 Chthonic');
INSERT INTO vinyl_author (author) VALUES ('鄧麗君 Teresa Teng');
INSERT INTO vinyl_author (author) VALUES ('宋冬野 ');
INSERT INTO vinyl_author (author) VALUES ('劉若英 ');
INSERT INTO vinyl_author (author) VALUES ('陳淑樺 ');
INSERT INTO vinyl_author (author) VALUES ('張艾嘉 ');
INSERT INTO vinyl_author (author) VALUES ('陳昇 Bobby Chen');
INSERT INTO vinyl_author (author) VALUES ('庾澄慶 Harlem Yu');
INSERT INTO vinyl_author (author) VALUES ('林慧萍 ');
INSERT INTO vinyl_author (author) VALUES ('艾怡良 ');
INSERT INTO vinyl_author (author) VALUES ('李玟 Coco Lee');
INSERT INTO vinyl_author (author) VALUES ('9m88 ');
INSERT INTO vinyl_author (author) VALUES ('孫盛希 ');
INSERT INTO vinyl_author (author) VALUES ('黃鶯鶯 ');
INSERT INTO vinyl_author (author) VALUES ('黃韻玲 ');
INSERT INTO vinyl_author (author) VALUES ('五月天 Mayday');
INSERT INTO vinyl_author (author) VALUES ('周蕙 ');
INSERT INTO vinyl_author (author) VALUES ('Dizzy Gillespie Charlie Parker');
INSERT INTO vinyl_author (author) VALUES ('王新蓮 ');
INSERT INTO vinyl_author (author) VALUES ('孫燕姿 ');
INSERT INTO vinyl_author (author) VALUES ('張洪量 ');
INSERT INTO vinyl_author (author) VALUES ('杜德偉 ');
INSERT INTO vinyl_author (author) VALUES ('江蕙 ');
INSERT INTO vinyl_author (author) VALUES ('辛曉琪 ');
INSERT INTO vinyl_author (author) VALUES ('許美靜 ');
INSERT INTO vinyl_author (author) VALUES ('Beyond ');
INSERT INTO vinyl_author (author) VALUES ('八三夭 ');
INSERT INTO vinyl_author (author) VALUES ('李宗盛 Jonathan Lee');
INSERT INTO vinyl_author (author) VALUES ('伍佰 & China Blue ');
INSERT INTO vinyl_author (author) VALUES ('潘越雲 ');
INSERT INTO vinyl_author (author) VALUES ('張懸 Deserts Xuan');
INSERT INTO vinyl_author (author) VALUES ('縱貫線 SuperBand');
INSERT INTO vinyl_author (author) VALUES ('周華健 ');
INSERT INTO vinyl_author (author) VALUES ('姜育恆 ');
INSERT INTO vinyl_author (author) VALUES ('張震嶽 ');
INSERT INTO vinyl_author (author) VALUES ('蘇慧倫 ');
INSERT INTO vinyl_author (author) VALUES ('王力宏 Leehom Wang');
INSERT INTO vinyl_author (author) VALUES ('任賢齊 ');
INSERT INTO vinyl_author (author) VALUES ('Cicada ');
INSERT INTO vinyl_author (author) VALUES ('鶴 The Crane');
INSERT INTO vinyl_author (author) VALUES ('HUSH ');
INSERT INTO vinyl_author (author) VALUES ('周傳雄 ');
INSERT INTO vinyl_author (author) VALUES ('蔡琴 ');
INSERT INTO vinyl_author (author) VALUES ('Calle Lindholm Musiikkiteatteri Ilona');
INSERT INTO vinyl_author (author) VALUES ('宇宙人 ');
INSERT INTO vinyl_author (author) VALUES ('嚴爵 Yen-j');
INSERT INTO vinyl_author (author) VALUES ('陳綺貞 Cheer Chen');
INSERT INTO vinyl_author (author) VALUES ('許茹芸 Valen Hsu');
INSERT INTO vinyl_author (author) VALUES ('動力火車 ');
INSERT INTO vinyl_author (author) VALUES ('白安 Ann');
INSERT INTO vinyl_author (author) VALUES ('縱貫線 ');
INSERT INTO vinyl_author (author) VALUES ('鄧紫棋 G.E.M.');
INSERT INTO vinyl_author (author) VALUES ('彭佳慧 Julia Peng');
INSERT INTO vinyl_author (author) VALUES ('曹格 ');
INSERT INTO vinyl_author (author) VALUES ('陳小霞 ');
INSERT INTO vinyl_author (author) VALUES ('梁靜茹 Fish Leong');
INSERT INTO vinyl_author (author) VALUES ('周杰倫 Jay Chou');
INSERT INTO vinyl_author (author) VALUES ('蔡健雅 Tanya');
INSERT INTO vinyl_author (author) VALUES ('徐懷鈺 Yuki');
INSERT INTO vinyl_author (author) VALUES ('張雨生 ');
INSERT INTO vinyl_author (author) VALUES ('王傑 ');
INSERT INTO vinyl_author (author) VALUES ('許景淳 ');
INSERT INTO vinyl_author (author) VALUES ('光良 ');
INSERT INTO vinyl_author (author) VALUES ('胡德夫 Ara Kimbo');
INSERT INTO vinyl_author (author) VALUES ('Lim Giong Various');
INSERT INTO vinyl_author (author) VALUES ('椅子樂團 The Chairs');
INSERT INTO vinyl_author (author) VALUES ('竇唯 ');
INSERT INTO vinyl_author (author) VALUES ('林憶蓮 ');
INSERT INTO vinyl_author (author) VALUES ('韋禮安 WeiBird');
INSERT INTO vinyl_author (author) VALUES ('張楚 ');
INSERT INTO vinyl_author (author) VALUES ('莫文蔚 ');
INSERT INTO vinyl_author (author) VALUES ('郭蘅祈 ');
INSERT INTO vinyl_author (author) VALUES ('小米 Johnny Tsai');
INSERT INTO vinyl_author (author) VALUES ('張惠妹 A-Mei');
INSERT INTO vinyl_author (author) VALUES ('吳青峰 ');
INSERT INTO vinyl_author (author) VALUES ('梅艷芳 ');
INSERT INTO vinyl_author (author) VALUES ('林強 ');
INSERT INTO vinyl_author (author) VALUES ('張國榮 Leslie Chang');
INSERT INTO vinyl_author (author) VALUES ('張學友 ');
INSERT INTO vinyl_author (author) VALUES ('A-Lin ');
INSERT INTO vinyl_author (author) VALUES ('Sandy Lam');
INSERT INTO vinyl_author (author) VALUES ('黃舒駿 ');
INSERT INTO vinyl_author (author) VALUES ('優客李林 ');
INSERT INTO vinyl_author (author) VALUES ('順子 ');
INSERT INTO vinyl_author (author) VALUES ('陶喆 ');
INSERT INTO vinyl_author (author) VALUES ('康康 ');
INSERT INTO vinyl_author (author) VALUES ('Leo王 ');
INSERT INTO vinyl_author (author) VALUES ('何勇 ');
INSERT INTO vinyl_author (author) VALUES ('徐若瑄 Vivian Hsu');
INSERT INTO vinyl_author (author) VALUES ('朱哲琴 DADAWA');
INSERT INTO vinyl_author (author) VALUES ('落日飛車 Sunset Rollercoaster');
INSERT INTO vinyl_author (author) VALUES ('王菲 ');
INSERT INTO vinyl_author (author) VALUES ('鳳飛飛 ');
INSERT INTO vinyl_author (author) VALUES ('新寶島康樂隊 ');
INSERT INTO vinyl_author (author) VALUES ('齊豫 ');
INSERT INTO vinyl_author (author) VALUES ('張宇 ');
INSERT INTO vinyl_author (author) VALUES ('陳奕迅 Eason Chan');
INSERT INTO vinyl_author (author) VALUES ('李志 Lizhi');
INSERT INTO vinyl_author (author) VALUES ('萬芳 ');
INSERT INTO vinyl_author (author) VALUES ('蘇芮 ');
INSERT INTO vinyl_author (author) VALUES ('兄弟本色 ');
INSERT INTO vinyl_author (author) VALUES ('趙傳 ');
INSERT INTO vinyl_author (author) VALUES ('王若琳 Joanna Wang');
INSERT INTO vinyl_author (author) VALUES ('朴彩英 Rose');
INSERT INTO vinyl_author (author) VALUES ('Sugar Babe ');
INSERT INTO vinyl_author (author) VALUES ('Linda Carriere (2) Linda Carriere (2)');
INSERT INTO vinyl_author (author) VALUES ('Nujabes ');
INSERT INTO vinyl_author (author) VALUES ('山下達郎 Tatsuro Yamashita');
INSERT INTO vinyl_author (author) VALUES ('菊池桃子 ');
INSERT INTO vinyl_author (author) VALUES ('中村遼 haruka nakamura');
INSERT INTO vinyl_author (author) VALUES ('竹內瑪麗亞 Mariya Takeuchi');
INSERT INTO vinyl_author (author) VALUES ('Natsu Summer ');
INSERT INTO vinyl_author (author) VALUES ('uyama hiroto ');
INSERT INTO vinyl_author (author) VALUES ('Hämäläis-Osakunnan Laulajat Juha Kuivanen');
INSERT INTO vinyl_author (author) VALUES ('芳野藤丸 ');
INSERT INTO vinyl_author (author) VALUES ('YOASOBI ');
INSERT INTO vinyl_author (author) VALUES ('King Gnu ');
INSERT INTO vinyl_author (author) VALUES ('具島直子 ');
INSERT INTO vinyl_author (author) VALUES ('MONDO GROSSO ');
INSERT INTO vinyl_author (author) VALUES ('大貫妙子 Taeko Onuki');
INSERT INTO vinyl_author (author) VALUES ('手嶌葵 ');
INSERT INTO vinyl_author (author) VALUES ('德永英明 Hideaki Tokunaga');
INSERT INTO vinyl_author (author) VALUES ('Ado ');
INSERT INTO vinyl_author (author) VALUES ('中森明菜 Akina Nakamori');
INSERT INTO vinyl_author (author) VALUES ('濱田金吾 ');
INSERT INTO vinyl_author (author) VALUES ('杏里 ANRI');
INSERT INTO vinyl_author (author) VALUES ('流線形 ');
INSERT INTO vinyl_author (author) VALUES ('The fin. ');
INSERT INTO vinyl_author (author) VALUES ('小野麗莎 Lisa Ono');
INSERT INTO vinyl_author (author) VALUES ('BTS 防彈少年團 ');
INSERT INTO vinyl_author (author) VALUES ('宇多田光 Utada Hikaru');
INSERT INTO vinyl_author (author) VALUES ('Junk Fujiyama ');
INSERT INTO vinyl_author (author) VALUES ('松原美紀 Miki Matsubara');
INSERT INTO vinyl_author (author) VALUES ('間宮貴子 Takako Mamiya');
INSERT INTO vinyl_author (author) VALUES ('羊文學 ');
INSERT INTO vinyl_author (author) VALUES ('嗜血屠夫 bloodthirsty butchers');
INSERT INTO vinyl_author (author) VALUES ('Mili ');
INSERT INTO vinyl_author (author) VALUES ('Solitude 2:14am ');
INSERT INTO vinyl_author (author) VALUES ('高橋竹山 ');
INSERT INTO vinyl_author (author) VALUES ('桑田佳祐 Keisuke Kuwata');
INSERT INTO vinyl_author (author) VALUES ('水原明子 Akiko Mizuhara');
INSERT INTO vinyl_author (author) VALUES ('BLACKPINK ');
INSERT INTO vinyl_author (author) VALUES ('藤井風 ');
INSERT INTO vinyl_author (author) VALUES ('RADWIMPS ');
INSERT INTO vinyl_author (author) VALUES ('岡本一生 Okamoto Issei');
INSERT INTO vinyl_author (author) VALUES ('Hiroshi II Hiroshi');
INSERT INTO vinyl_author (author) VALUES ('亞蘭知子 ');
INSERT INTO vinyl_author (author) VALUES ('青葉市子 Ichiko Aoba');
INSERT INTO vinyl_author (author) VALUES ('林哲司 ');
INSERT INTO vinyl_author (author) VALUES ('Noriki ');
INSERT INTO vinyl_author (author) VALUES ('Kiyoshi Yamaya Kiyoshi Yamaya');
INSERT INTO vinyl_author (author) VALUES ('Pictured Resort ');
INSERT INTO vinyl_author (author) VALUES ('富田勳 Isao Tomita');
INSERT INTO vinyl_author (author) VALUES ('G.Yoko ');
INSERT INTO vinyl_author (author) VALUES ('DJ Yoshizawa Dynamite.jp Chintam');
INSERT INTO vinyl_author (author) VALUES ('大橋純子 Junko Ohashi');
INSERT INTO vinyl_author (author) VALUES ('佐藤博 Hiroshi Sato');
INSERT INTO vinyl_author (author) VALUES ('鈴木宏昌 Hiromasa Suzuki');
INSERT INTO vinyl_author (author) VALUES ('大瀧詠一 Eiichi Ohtaki');
INSERT INTO vinyl_author (author) VALUES ('Various DJ Yoshizawa Dynamite.jp');
INSERT INTO vinyl_author (author) VALUES ('福居良 Ryo Fukui');
INSERT INTO vinyl_author (author) VALUES ('今井美樹 Miki Imai');
INSERT INTO vinyl_author (author) VALUES ('Mr.Children ');
INSERT INTO vinyl_author (author) VALUES ('Nick Luscombe');
INSERT INTO vinyl_author (author) VALUES ('池玲子 ');
INSERT INTO vinyl_author (author) VALUES ('池田典代 Noriyo Ikeda');
INSERT INTO vinyl_author (author) VALUES ('井上鑑 Akira Inoue');
INSERT INTO vinyl_author (author) VALUES ('Sing Like Talking');
INSERT INTO vinyl_author (author) VALUES ('吉田美奈子 Minako Yoshida');
INSERT INTO vinyl_author (author) VALUES ('米希亞 MISIA');
INSERT INTO vinyl_author (author) VALUES ('Happy End ');
INSERT INTO vinyl_author (author) VALUES ('松田聖子 Seiko Matsuda');
INSERT INTO vinyl_author (author) VALUES ('金延幸子 Sachiko Kanenobu');
INSERT INTO vinyl_author (author) VALUES ('安全地帶 Anzen Chitai');
INSERT INTO vinyl_author (author) VALUES ('Bronze ');
INSERT INTO vinyl_author (author) VALUES ('月之海 LUNA SEA');
INSERT INTO vinyl_author (author) VALUES ('黃色魔術交響樂團 Yellow Magic Orchestra');
INSERT INTO vinyl_author (author) VALUES ('Presents ');
INSERT INTO vinyl_author (author) VALUES ('漢斯季默 Hans Zimmer');
INSERT INTO vinyl_author (author) VALUES ('Kouichi Sugiyama Koji Kondo');
INSERT INTO vinyl_author (author) VALUES ('Various Lin-Manuel Miranda');
INSERT INTO vinyl_author (author) VALUES ('赫胥卡 Hauschka');
INSERT INTO vinyl_author (author) VALUES ('蓋布瑞雅德 Gabriel Yared');
INSERT INTO vinyl_author (author) VALUES ('Clément Ducol Camille');
INSERT INTO vinyl_author (author) VALUES ('約翰戈爾特勒 John Gurtler');
INSERT INTO vinyl_author (author) VALUES ('崔特雷澤諾 Trent Reznor');
INSERT INTO vinyl_author (author) VALUES ('布萊恩泰勒 Brian Tyler');
INSERT INTO vinyl_author (author) VALUES ('丹尼葉夫曼 Danny Elfman');
INSERT INTO vinyl_author (author) VALUES ('Masayoshi Soken');
INSERT INTO vinyl_author (author) VALUES ('Stephen Schwartz');
INSERT INTO vinyl_author (author) VALUES ('宮川泰 ');
INSERT INTO vinyl_author (author) VALUES ('哈利葛瑞森-威廉 Harry Gregson-Williams');
INSERT INTO vinyl_author (author) VALUES ('various');
INSERT INTO vinyl_author (author) VALUES ('Colin Stetson');
INSERT INTO vinyl_author (author) VALUES ('CthulhuSeeker');
INSERT INTO vinyl_author (author) VALUES ('唐戴維斯 Don Davis');
INSERT INTO vinyl_author (author) VALUES ('布萊恩伊諾 Brian Eno');
INSERT INTO vinyl_author (author) VALUES ('Fire Bomber');
INSERT INTO vinyl_author (author) VALUES ('八草樂團 ');
INSERT INTO vinyl_author (author) VALUES ('亞倫席維斯崔 Alan Silvestri');
INSERT INTO vinyl_author (author) VALUES ('野見祐二 ');
INSERT INTO vinyl_author (author) VALUES ('My First Story Hyde (5)');
INSERT INTO vinyl_author (author) VALUES ('艾美懷絲 Amy Winehouse');
INSERT INTO vinyl_author (author) VALUES ('布萊斯戴斯納 Bryce Desnner');
INSERT INTO vinyl_author (author) VALUES ('London Music Works ');
INSERT INTO vinyl_author (author) VALUES ('Kouichi Sugiyama');
INSERT INTO vinyl_author (author) VALUES ('伊莫珍希普 Imogen Heap');
INSERT INTO vinyl_author (author) VALUES ('大野雄二 ');
INSERT INTO vinyl_author (author) VALUES ('桑塔歐拉拉 Gustavo Santaolalla');
INSERT INTO vinyl_author (author) VALUES ('地下絲絨 The Velvet Underground');
INSERT INTO vinyl_author (author) VALUES ('安德烈洛伊韋伯 Andrew Lloyd Webber');
INSERT INTO vinyl_author (author) VALUES ('拉敏賈瓦帝 Ramin Djawadi');
INSERT INTO vinyl_author (author) VALUES ('Frank Montasell ');
INSERT INTO vinyl_author (author) VALUES ('湯瑪士紐曼 Thomas Newman');
INSERT INTO vinyl_author (author) VALUES ('布倫丹安吉利斯 Brendan Angelides');
INSERT INTO vinyl_author (author) VALUES ('亞蘭葛拉格 Alain Goraguer');
INSERT INTO vinyl_author (author) VALUES ('Jacek Paciorkowski ');
INSERT INTO vinyl_author (author) VALUES ('魯德溫葛瑞森 Ludwig Goransson');
INSERT INTO vinyl_author (author) VALUES ('佐藤直紀 ');
INSERT INTO vinyl_author (author) VALUES ('馬汀菲皮斯 Martin Phipps');
INSERT INTO vinyl_author (author) VALUES ('菅野洋子 ');
INSERT INTO vinyl_author (author) VALUES ('影山ヒロノブ＆Broadway');
INSERT INTO vinyl_author (author) VALUES ('Make-up');
INSERT INTO vinyl_author (author) VALUES ('Hiroshi Kitadani Akemi Okamura');
INSERT INTO vinyl_author (author) VALUES ('Jongnic Bontemps');
INSERT INTO vinyl_author (author) VALUES ('初音未來 初音ミク');
INSERT INTO vinyl_author (author) VALUES ('Akira Yamaoka Marcin Przybyłowicz');
INSERT INTO vinyl_author (author) VALUES ('羅比羅伯森 Robbie Robertson');
INSERT INTO vinyl_author (author) VALUES ('牛尾憲輔 Kensuke Ushio');
INSERT INTO vinyl_author (author) VALUES ('布拉格城市愛樂 City of Prague Philharmonic');
INSERT INTO vinyl_author (author) VALUES ('畢奇奧尼 Piero Piccioni');